alias clj='rlwrap java -cp ~/Clojure/clojure-1.8.0.jar clojure.main'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias gpwd="pwd | xclip -i"
alias cdpwd="cd \$(xclip -o)"
alias m='gnome-mpv'
alias ml='livestreamer --config ~/.livestreamerrc -v'
alias jblive='gnome-mpv rtmp://jblive.videocdn.scaleengine.net/jb-live/play/jblive.stream'
alias twit='livestreamer --config ~/.livestreamerrc -v http://www.ustream.tv/leolaporte'
