set number
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set visualbell
set hlsearch
set smartcase
set ignorecase
set incsearch
set autoindent
set shiftwidth=3
set smartindent
set softtabstop=3
set ruler
set undolevels=1000
set backspace=indent,eol,start
syntax on
